### ISSUE TITLE
Support for RFM98 LoRa

### ISSUE THREAD

**Issue by mattwilliamson** [jpnorair/OpenTag#12]
I saw your blog post that LoRa is the future for DASH7. Let's make it happen. I'm willing to help, contingent on pointers to get STM32L0 working as well.

**Comment by jpnorair** [comment]
More generally, I would say that modulations optimized for long range are the future for the DASH7 PHY.  LoRa is one of them.  Frankly, I think I can beat LoRa using homegrown DSSS and signal processing techniques on something like the CC1310, but that's a fair bit of work.  With LoRa, the work is mainly done.  LoRaWAN is kind of limited in what it does.  I'd like to offer a better solution for ad-hoc communication, using LoRa, rather than the sort of "beacon every 10 minutes" setup that LoRaWAN is designed mainly to do.

What you can start doing, if you like STM32L0, is to get that platform working.  There is an issue with the interrupt functionality, but with a bit of time I'm sure it can be debugged.

**Comment by jpnorair** [comment]
SX1272 via ST's LoRa Nucleo (Nucleo LRWAN1) is now supported.  Would be great if you wanted to modify the board header for RFM98 -- should be easy.
